let intro_title_eng = "In the Wonderful World of Football";
let intro_eng = ["The 'Favela' (South American shanty town) is a typical subject for reportage photography, a genre with a long tradition that too often and for a variety of reasons, offers a narrow and clichéd view, both aesthetically and in the way that it portrays people and their circumstances. The initiation of photography workshops at the Favela do Morro do Cascalho in Belo Horizonte, Brazil, was to a certain extent, a reaction against that particular kind of representation; an attempt to offer an alternative approach, totally dependent upon the active and creative involvement of the participants.",
                "Photography, stripped down to it's essentials, is actually a simple and generous medium. The act of pressing the shutter is so easy, yet the fleeting moment that is recorded on film may provide endless fascination and be a beautiful, complex and emotive social document. The idea, therefore, was to equip favela children with cheap 'point and shoot' cameras with flash and colour film, and to encourage them to use photography to express their feelings and explore the relationship between football and their community.",
                "Cascalho was selected due to its explicit engagement with football - the entrance to the favela is the football pitch. The Community Association, the product of an extremely poor, but stable and closely - knit neighborhood, responded to the proposal with great enthusiasm and helped with the preparation and organization. The photography workshop involved 41 boys aged 8 to 14 who were active participants in the children's football team and nine girls between the ages of 14 and 30 from the women's team. Over a period of two weeks they each exposed four or five rolls of film.",
                "None of them had ever had the opportunity to take photographs before and as a result they were not restrained by conventional notions of what makes a good picture. Their approach was direct, curious, candid, unpretentious and honest. They have produced extraordinary, totally uninhibited photographs; photographs that convey hopes, fears, dreams and fantasies, but which remain vividly rooted within the realities of their lives in the favela.",
                "The following year we asked the children to make paintings. Their spontaneous inclination to depict footballs, football pitches, football shirts and trophies as symbolic, beautiful icons and their natural affinity with colour has produced a beautiful series that perfectly complements the photographs. For this book, in a process that involved the whole community, they have also put their story down in words. During many meetings and discussions their stories blossomed into a collective history of Cascalho. Their words, in unison with their images, convey a love for football and are a fascinating account of its significance in their lives. Football, for them, is everywhere. It has a physical presence in their homes, in the clothes they wear, in their landscape and most certainly in their hearts and minds.",
                "It is an integral part of their culture.",
                "No Mundo Maravilhoso do Futebol is a reflection of their attitude to the world's most popular game, a perfect fusion of four beautiful means of expression: painting, photography, writing and football."]
let intro_title_pt = "No Mundo Maravilhoso do Futebol";
let intro_pt = ["A favela é um tema comum nas reportagens fotográficas - um gênero de longa tradição -, que frequentemente e por varias razões, apresenta uma visão cheia de clichês, na maneira como retrata as pessoas e suas circunstâncias o projeto das oficinas de fotografia na favela do Morro do Cascalho em Belo Horizonte, Brasil, foi de um certo modo uma reação contra essa forma particular de representação, uma tentativa de oferecer uma visão totalmente dependente do envolvimento ativo e criativo dos participantes.",
            "A fotografia, reduzida ao essencial, é uma linguagem simples e generosa. O ato de apertar o botão do disparador é fácil e possibilita transformar um instantâneo num complexo e emotivo documento social. A idéia foi equipar as crianças da favela com câmeras com flash do tipo aponte e dispare' e filmes coloridos, encorajando-as a usar a fotografia para expressar seus sentimentos, explorando as relações entre o futebol e sua comunidade. O Morro do Cascalho foi escolhido devido a seu explícito engajamento com o futebol, a própria entrada da favela é um cambo de futebol.",
            "A Associação Comunitária foi procurada e respondeu a nossa proposta com grande entusiasmo ajudando na preparação e organização do esquema de trabalho. As oficinas de fotografia envolveram 41 meninos, entre 8 e 14 anos, que estavam inscritos no time infantil e 9 moças, entre 14 e 30 anos, inscritas no time feminino. Num período de duas semanas cada um teve a oportunidade de expor quatro ou cinco rolos de filme.",
            "Nenhum deles nunca tivera a oportunidade de tirar fotos antes e por isso não estavam presos a noções convencionais ‘de como fazer uma boa fotografia’. As imagens por eles realizadas são diretas, curiosas, cândidas e despretensiosas. Eles produziram fotografias extraordinárias e totalmente desinibidas, que expressam seus desejos, medos, sonhos e fantasias e que estão vivamente enraizadas na realidade em que vivem.",
            "Um ano depois convidamos as crianças a participarem de oficinas de pintura. Eles fizeram campos de futebol, bolas, uniformes e troféus simbólicos e bonitos ícones. Com sua natural afinidade com as cores, produziram uma série de trabalhos que complementam perfeitamente suas fotografias.",
            "Para esse livro, num processo que envolveu toda a comunidade, as crianças procuraram trazer a tona as histórias do morro em suas próprias palavras. Após muitos encontros e discussões, esses textos foram editados e costurados, transformando-se num relato coletivo da História do Cascalho. Suas palavras, em uníssono com suas imagens, mostram seu amor pelo futebol e a fascinação que ele exerce em suas vidas.O futebol está em todo lugar, é uma presença física em suas casas, nas roupas que eles usam, na paisagem, e mais certamente em seus sonhos.",
            "No Mundo Maravilhoso do Futebol é reflexo da atitude dessas crianças para com o esporte mais popular do mundo, uma perfeita fusão de quatro bonitos meios de expressão: pintura, fotografia, escrita e futebol."]


let history_title_eng = "The History of Cascalho";
let history_eng = ["In the beginning there was nothing, not a stone or a tree. Dinosaurs were everywhere. There was only one little house, far in the distance; Eve and Adam's. They made a bomb and destroyed all the dinosaurs. Then, Adam and Eve made us and sent us to live here in Cascalho. Then came chickens, dogs, birds, horses, cats, pigs, rabbits, goats, rats, cockroaches and many more people.",
                        "Cascalho is a favela (shanty town): not a farm and not in the country. It is not really like in the city, but the city is all around us. I was born here and now I am being raised here. It is a wonderful place for those who are used to living with all kinds of people; happy, sad, etc. Here, everybody tries to help each other. The favela is the hill and our hill gives an open view of the city and the entrance to the favela is the football pitch.",
                        "In olden times Cascalho was just covered with bushes and trees. When people first came here - to this land full of nothing - where the main road is now there was just a path in the scrub land and there was no access for busses, trucks or horses with carts. Building was a difficult job since there was no water or bricks, or money.",
                        "They used canvas, lumber and adobe and also cardboard, tin and plywood. The settlers made a lot of adobe with their own hands, using earth and dirty water which they collected from the washer women in the neighborhood. Gradually, more people who had nowhere to live came and they started to hoe and to build too. The place was taking shape through the effort of the men and women who came to build their simple and humble houses.",
                        "In those das there were two big rocks to climb and it is said that you could watch the city in the distance as well as fun fairs and circus’s from up there. There were only a few buildings spread around here, but as the city grew bigger, it came closer and closer to Cascalho. Rich people came to buy plots of land, but they had to leave their cars at the bottom of the hill and climb up by foot. People say that close to where my house is now there was another big rock, even bigger than my house. One day it rolled down the hill, rolled and rolled all the way as tar as the small square at the bottom. In the fall the rock smashed into millions of little pieces like gravel, which scattered everywhere. That is the origin of the name ‘Morro do Cascalho' - Gravel Hill.",
                        "Where the football pitch is there used to be a steep slope and there were gullies and weeds everywhere. Where the little church stands now there was just a cross, with a beautiful view. If the weather was dry for too long old people brought water to throw at the feet of the cross. Then the rain would fall.",
                        "The hill had no piped water. The people fetched it on their heads or by donkey from a big pump all the way down there, where Anita Garibaldi street is today. There were no electric lights and people used candles, kerosene or gas lamps and everybody did the best they could.",
                        "Then came the light. Only one man had a TV set. If people wanted to watch they had to deliver a barrel of water to his house. Those were good as well as difficult times. Today, we could not live like those pioneers, with no water, sewerage or even a dribble of light. Nowadays, we fight in heaven.",
                        "The church is dedicated to ‘Saint Ermelinda’. Some people say that she is the patron saint of Cascalho and Catholics. Others say that she is only the patron saint of the priest and isn't recognized by the Vatican. The priest does not allow poor people in to the church, only wealthy people. Never, not even once, not even on sacred days have we been in the church. It is said that inside there is a statue of Saint Ermelinda and that water pours through her hands and there is a tunnel of light where people are given gifts.",
                        "Cascalho starts behind the goal posts of the football pitch continuing up to the end of Anita Garibaldi Street and Nascimento Gurgel Street. It's main alleys are Nervous Tony's Alley, Chiquita's Alley, Adilson's Alley, Scar Alley, Liberty Alley, Little Rice Alley. Assembly Alley, etc. Over time, some of the alleys have been improved with stone or concrete to make a pavement. Some were made wider, while some others have become squeezed by new fences and walls. The favela spreads across the hill, it covers a multitude of things and ends at a small and hidden house which can only be seen when you come right up to it. From the other side of the main road you can see almost the whole of Belo Horizonte, the blue sky as well as the pink pollution.",
                        "We are proud of this privileged view and it is not only us that likes it, because we nave seen quite a few people from a more evicacious class come up here to enjoy it. At night we look at the stars and the cars passing by. Once I saw a falling star, made a wish and put a small stone under my pillow. The wish became reality.",
                        "The people of Cascalho do not own the land, but we have been here for many years and we have some rights. But because of the construction companies and the increasing value of land in the city, the favela is being squashed. The favela is worth nothing to them as a favela. Wealthy people are invading the hill. Now there are loads of new buildings and they are becoming bigger and bigger and making our place ugly. They are even building where our neighbours houses used to be.",
                        "There are all kinds of people living here, working people doing their best for themselves and their children. Most were born on the hill, while others come from the hinterland of the state of Minas Gerais and also from the states of Pernambuco and Ceará. Many moved here from living rough under the bridges or wherever. I would prefer it if the favela didn't exist. Nobody lives in a favela by choice, but because they have very little money. I want to live here, where l was born, but l wish that Cascalho could change from being a ‘shanty’ town to being a town as soon as possible.",
                        "Many people work with horses and carts or cars and vans. Some work in the sewers; others work washing and ironing clothes, as house keepers, baby sitters, cooks, policemen, janitors, housewives; or sell hot dogs; or collect waste paper, scrap metal and used cans in a big wheelbarrow; work as doormen, bricklayers labourers, gardeners, joiners, night-watchmen, plumbers, electricians, bus drivers, receptionists, etc. Some people have good jobs and earn more while others earn very little and some even live as vagabonds.",
                        "My house has always been here. House? Yes. We have huts but we call them houses. The street I live in is very dirty, but my house is clean because | take care of it. My house is next door to my brother's. After he got married, he built an extension onto my mother’s house. My house has a bathroom, a dining room with a sofa and TV, a kitchen and three bedrooms. I put my favorite things in my bedroom. There is also another room which is a bar where we sell beer, etc. We have a fridge, cupboard, shelves, cooker and a music set. A few people have videos and cable TV. l have seven brothers and when you add my nephews and sister-in-law, there are more than eleven of us at home. In bed at night l feel safe and relaxed, but sometimes | can't help thinking about the future; scared of just becoming a nobody.",
                        "When it's raining the stink is not so bad. There is less dust but it gets so muddy that we can hardly get out of our houses. People try to keep dry but a little water never killed anybody. On rainy das the best thing is to stay indoors, huddle together under a blanket and watch TV, maybe with some savoury popcorn and a family sized bottle of pop. When there is thunder and lightening we turn the mirrors to the wall and do not use forks.",
                        "Most kids help their parents at home, but even when they are very young they go out to work, doing things like carrying people's shopping at the supermarket, watching people's cars or working at the market. There are some kids that give their mothers a lot of trouble! The important thing is not to steal and to keep healthy so that you are strong enough to deal with the ups and downs of life. We study and play with balls, kites and marbles. We play ring-a-ring-a-rosy, hide and seek, steal the flag, cops and robbers, statues, follow the leader, hopscotch, etc. Some of the games can get quite rough. Even it we are not playing games, all the interesting things that happen around here keep us happy.",
                        "Most of all we love football. We couldn’t live without football. The most important event in the history of Cascalho was the construction of the football pitch. This brilliant idea was born during a really smart chitchat. It was built in 1973. The people did everything. It was all their own work, with determination and much hard labour. It was done by hand. They cut the weeds with a scythe and they began to dig with shovels, hoes and pickaxes. Many trucks of soil were needed to level the field which was sloping almost as far down as the electricity pylon. In the end they managed to obtain a machine to get the pitch as flat as possible and make it pretty much like it is today.",
                        "Then the first soccer club on the hill was founded, called Benfica, with a black and white kit. When they went to register they discovered there was another local club already using the name. At the last minute they decided to register our glorious team as Grajaú Esporte Clube. We have children’s, women’s and men’s teams The strip was changed to blue and white. A team must have a proper kit if it is to become popular. We also have a flag, trophies and faithful supporters.",
                        "Once, on a Good Friday, a contractor came and built a wall halfway across the pitch. Everybody was shocked and it was decided the wall must be smashed down. We decided it and then we did it; we chased the security guard away, destroyed the wall and organised a match to commemorate the occasion. If we had acted softly, we would have lost the only sports ground in the area and the most important collective effort on the hill would have been for nothing. I was not born when all of this happened, but my mother told me as l was growing up. This is important in our history, even today.",
                        "If only the pitch had lovely green grass, so it wouldn't be so muddy when it rains, leaving our shirts hard to wash. It is not the best for showing our football skills, but we like it the way it is, crooked, full of stones, a few holes and only a little grass. We don't have a fence around the pitch or appropriate accommodation for the supporters. The main problem at the moment is that during a match the ball often lands in somebodies house and certain people refuse to give it back.",
                        "As well as football, there are many parties and festivals. We love it when everybody dances the ‘Pagode', a kind of samba but more relaxed. During the Carnival we all have as much fun as possible. They play the 'Game of Whores', when the men dress up as women, wearing wigs, miniskirts and lots of lipstick. At the end of Lent we burn Judas, but before he is burnt, his testament - scandalous gossip and hearsay from around the favela - is read aloud. There are a lot of jokes and it Is very funny, out many people don't like to be scolded by Judas!",
                        "We have many happy times but there are also problems. There are a lot of petty arguments, but you know it’s getting really serious if somebody insults your mother, even if your mother has nothing at all to do with it.",
                        "The main road is very dangerous, especially for the kids that are too innocent to cross the street. The cars go very fast. Maybe that's just how people drive, or it could be because they are afraid of the favela. The tranquillity is occasionally shattered by gunshots because there are a few really lazy people who get into fights. When the police come they can never catch them because they disappear deep into the heart of the favela. When they get home they go up the wall and they get stoned out of their minds.",
                        "There are some stories from around here that have become legends. There is the one about the werewolf who appears when the moon is full. Everybody is terrified of him because he is enormous and his body is totally hairy, covered from his brain to his toes. He has a thin moustache made from wire and he eats live ants. It's lucky I've never seen him! There is another story about ‘Comanche’, a brown horse with white spots. One day a woman called Adélia was walking past Comanche when he spoke. He said, ‘Good night Adélia’! She ran to Consola's house and fainted. Then, a young man nicknamed Jó also heard the horse speak: 'Oh Jó, how good it is to live in this world’. What a crazy horse! It Is legendary that horses can talk with people. Actually, we do talk to the horses, and they understand us, but usually they do not answer in words.",
                        "We sat around 'Old Man Tiao' while he told us these stories. When we didn't believe him he waggled his ears and laughed so much that we will remember it for ever There are other unforgettable and happy moments, like the trips we make to away games with our football team. These moments deserve a slow motion action replay, but since that is not possible we just record them in our memory.",
                        "It is a great honour for us to tell our history in a book, where our lives can be read and re-read by a lot of people. In this story made by all of us together, we dug a lot of things out of the old trunk, and there aren't any really big lies. Everything that Is written here is what we have been told and most of us believe that even the legends are true.",
                        "After all, so many incredible things happen in the world."]
let history_title_pt = "História do Cascalho";
let history_pt = ["No começo do mundo não tinha nada. nem uma pedra e nem uma árvore. Tudo era cheio de dinossauros. Só tinha uma casinha bem longe, era de Eva e Adão. Eles fizeram uma bomba e atiraram nos dinossauros todos. Aí, Adão e Eva fez nós e fez a gente viver aqui no Cascalho. Veio viver também galinha, cachorro, passarinhos, cavalo, gato, coelho, cabrito, rato, barata, e muito mais gente.",
                        "O Cascalho é uma favela, não é uma fazenda e não é uma roça. Aqui eu nasci e estou sendo criado. É um lugar formidável para quem é acostumado a viver com pessoas diferentes, alegres, tristes e etc. Aqui todo mundo tenta ajudar o outro mesmo não conseguindo. A favela é o morro e o nosso morro é uma vista aberta para a cidade, com um campo de futebol na entrada.",
                        "No principio o Cascalho era apenas um lugar coberto de matas. Quando o pessoal veio pra cá não tinha passagem de carros e caminhão, ônibus, carroça e etc. Tinha uma rua de mato que é essa rua de asfalto que está aqui agora. Aí, mais pessoas que não tinham onde morar viram o terreno todo cheio de nada, pegaram a capinar e construir também. Construir era difícil: não tinha água ou tijolo, nem dinheiro para comprar material. Por isso, começaram a construir as casas de lona, tábua e adobe, umas também de papelão, latão e 'Madeiriti”. Muito adobe foi feito pelas nossas mãos com terra e águas das roupas lavadas pelas vizinhas. Aos poucos o lugar foi tomando forma pelos moradores que foram chegando e construindo suas casas simples e humildes.",
                        "Antigamente tinha dois ‘pedrão’ de subir e ficar olhando a cidade e sempre vinha para o morro parque e circo, que eram a nossa alegria. Quando o bairro chegou aqui perto quem tinha carro teve que deixa-lo embaixo e subir pra comprar lotes a pé. Nessa época a vista era uns prédios lá na frente da cidade, todos uns longe dos outros. Dizem que lá perto de onde é a minha casa tinha uma grande pedra, maior que a minha casa. Um dia ela foi rolando, rolando e parou na pracinha lá embaixo. Da pedrona foi soltando cascalho prá todo lado. Dai velo o nome de Morro do Cascalho.",
                        "Este campo que tem aqui era uma rampa, um barranco com capim prá todo lado, e, onde é a igrejinha, era um cruzeiro. Quando ficava muito tempo sem chuva, as pessoas de idade colocavam água na cabeça e iam jogar no pé do cruzeiro. Aí, a chuva caía.",
                        "No morro não tinha aqua encanada. Os moradores buscavam água na cabeça e na carroça, lá do torneirão onde hoje é a Rua Anita Garibaldi. Naquela época também não tinha luz e as pessoas usavam velas e luminavam com querosene, e também com o ‘liquinho’ e cada um se virava como podia.",
                        "Depois veio a luz. Só tinha TV na casa de uma pessoa. Quando a gente queria assistir, tinha que encher tambor de agua e carregar para a pessoa. Tempos bons e difíceis ao mesmo tempo. Hoje lutamos no céu. Não sofremos como antigamente o pessoal sofria, sem encanamento, esgoto e nem um ‘fiinho’ de luz. A igrejinha é de Santa Ermelinda. Dizem que a santa era padroeira dos moradores do Cascalho e de católicos. Outros dizem que a santa é padroeira do padre e que não é reconhecida no Vaticano. Dizem que tem sua imagem lá dentro e ela solta água pelas mãos e que tem também um túnel todo de luzes onde o povo ganha coisas. Mas, o padre não deixa entrar pobre na igreja, só rico, nunca, em época nenhuma, nem em ocasião sagrada.",
                        "O Cascalho começa pela beirada das traves do campo e vai até o final da Rua Anita Garibaldi e da Rua Nascimento Gurgel. Seus becos principais são o Beco do Toninho Nervosia, Beco da Chiquita, Beco do Adilson, Beco Cicatriz. Beco Liberdade. Beco do Arrozinho, Beco da Assembléia, etc. Com o tempo alguns foram melhorados com calçamento de paralelepípedos e massas de concreto, uns foram se alargando enquanto outros se estreitando pelas cercas e muros. A favela segue pelo morro e acaba numa casa bem escondidinha e que ninquém vê, so quando vai lá. As laterais acabam no outro lado da rua, de onde a gente avista quase toda Belo Horizonte, o céu azul e também a poluição lilás.",
                        "Temos o prazer de ver essa vista privilegiada, que não agrada somente a nós pois por diversas vezes surpreendemos pessoas de classe mais eficaz dividindo conosco a paisagem. À noite a gente fica olhando as estrelas e os carros passando. Um dia eu vi uma estrela cadente fiz um pedido, pequei uma pedrinha e coloquei debaixo da cabeceira e o desejo se realizou.",
                        "Devido as indenizações o morro está ficando menor e a favela esta diminuindo o seu valor como favela, está sumindo e está vindo à tona o seu valor como bairro. Hoje está tudo valorizado. Os ricos querem invadir a favela. Os prédios se multiplicaram e ficam cada vez maiores, ‘enfeiando’ nosso morro e se plantando no lugar onde antes eram as casas dos nossos vizinhos.",
                        "Aqui vivem vários habitantes, pessoas trabalhadoras que procuram dar sempre o melhor de si para seus filhos. A maior parte nasceu no morro, outros vieram de muitos lugares do interior dos estados de Minas Gerais - Ponte Nova, Santo Antônio do Grama, Ouro Preto, Rio Casca, Brumado, São Sebastião do Morão, São José do Goiabal, Serro, Matipó, Passos, Dores do Indaiá -, Pernambuco e Ceará. Muita gente veio de debaixo da ponte e de outros lugares. A maioria é de pessoas que são mineiras, baianos e da roça. Não queria que favela existisse, ninguém mora em favela por opção, mas pela condição de não ter dinheiro. Queria morar aqui onde eu nasci e que o meu morro virasse meu bairro o mais depressa possível. Muitas pessoas trabalham com carroças e cavalos e carros e Fusca e Kombi. Outros trabalham de costureiras, lavadeiras, faxineiras, babás, cozinheira, operário, policia, zelador, passadeiras de roupa, donas de casa. Ou trabalham com carrinho de cachorro quente, carrinho de mão para transporte de papéis, ferro velho e latinhas, porteiro, servente, pedreiro, garagista, jardineiro, carpinteiro, guarda noturno, bombeiro, eletricista, marceneiro, motorista, recepcionista, etc. Uns trabalham com um cargo maior e ganham mais, outros ganham menos, outros vivem de vagabundos.",
                        "A minha casa sempre foi aqui. Casa sim, porque temos barracos e dizemos casas. A minha rua é muito suja, mas a minha casa é muito limpinha porque eu arrumo. Minha casa é parede meia porque o meu irmão casou e está morando em parede meia com a minha mãe. A casa tem um banheiro, uma sala com sofá e TV, também tem uma cozinha, três quartos e no meu quarto tem meus enfeites. Também tem um boteco. Temos geladeira, armário, estante, fogão, som. Uns têm video e TV a cabo. Tenho sete irmãos e contando com meus sobrinhos e cunhados são mais de onze aqui em casa. Sempre à noite na minha cama fico confortável e espichado e me sinto todo relaxado. Às vezes fico pensando no amanhã, porque tenho medo de um dia não ser ninguém.",
                        "Quando chove apaga a catinga, abaixa a poeira, mas faz tanto barro que a gente quase não pode sair. As pessoas tentam esconder debaixo de um teto, mesmo molhando porque pouca água não mata ninguém. Nesses dias o programa é juntar debaixo da coberta e ficar assistindo TV, quem sabe comendo uma pipoquinha saborosa acompanhada por um refrigerante família. Quando relampeia a gente vira o espelho e não come de garfo.",
                        "Muitas crianças ajudam os pais desde cedo nas tarefas de casa e já começam a trabalhar fora muito novas - fazem carreto, vigiam carros e trabalham em sacolão - e outras dão muito trabalho para as mães. O importante é não roubar e ter saúde para o que der e vier. Os meninos estudam e brincam de bola, papagaio, bolinha de gude, roda, pega-pega, rouba bandeira, policia e ladrão, corre-cutia, duro e mole, boca de forno, vai-ali-vai-ali, estrela, novo toco, cai do posto, maré, caracol, queimada e finca. Só não abrem mão, de jeito nenhum, do futebol. Eles também brigam e gostam de outras coisas que acontecem. A história mais importante do morro e a da construção do campo de futebol. A brilhante idéia nasceu num bate papo realmente inteligente que concluiu pela fundação do campo. Ele foi construído em 1973. Foram os moradores que começaram tudo, foi tudo obra deles, força de vontade e muito trabalho pesado. Aconteceu de forma artesanal: com foice cortaram o mato, com pá, enxada e picareta foram construindo. Foi preciso muitos caminhões de terra para acertar o campo, aterrando a rampa que descia quase até onde está a antena. Depois arrumaram uma máquina para acertar o campo, aplainaram e fizeram a melhoria que está aí.",
                        "Logo após foi fundado o primeiro clube de futebol do morro, chamado Benfica, que jogava com o uniforme preto e branco. Ficou assim até que foram registrar o time e já existia outro com o mesmo nome. Na hora ‘h’ sugeriram registrar nosso glorioso time como Grajau Esporte Clube, nas categorias infantil, feminino e veteranos O nosso uniforme passou para azul e branco e é primordial ao nosso time, porque sem uniforme o time não fica popular. Temos também bandeira, troféus e uma torcida fiel.",
                        "Certa vez, numa sexta-feira da paixão, veio uma construtora e murou a metade do campo. Todo mundo estava chocado quando surgiu a idéia de pôr o muro a baixo. Dito e feito: pusemos o vigia prá correr, derrubamos o muro e marcamos um jogo prá comemorar. Se a gente desse mole, perdia a única praça de esportes que temos e a maior obra coletiva do morro. Quando aconteceu isso tudo eu não tinha nascido, mas minha mãe contou tudo para mim quando eu cresci e fui crescendo. É uma longa história até hoje. Queria que o campo fosse todo gramado de verde para quando chover não ficar aquela água toda suja no meio e os uniformes ficarem difíceis de lavar. Nosso campo não é o menor para mostrar nosso futebol, mas gostamos dele como ele é, torto, cheio de pedra, um pouco de grama e com alguns buracos. Sem tela e lugar apropriado para a torcida, o único recente problema é que quando jogamos, a bola cai nas casas e os vizinhos não querem saber de devolver.",
                        "Um bom programa além de um jogo no campo, é o que as famílias combinam umas com as outras prá fazer. Gosto quando tem um pagodinho - o eterno - onde todo mundo samba, canta e outras coisas mais. Tem também muitas festas. No Carnaval todos se divertem como podem, cada um à sua maneira. Na terça-feira gorda rola o chamado ‘Jogo das Putas’ que são os homens jogando futebol vestidos de mulher, com peruca, minissaia, muito batom e etc. No final da quaresma, no sábado de aleluia, tem a queima do Judas. Ele é gordo prá queimar mais bonito e fazer mais graça. Antes de queimar tem a hora que alguém lê o testamento que o Judas deixou para cada um, onde conta as fofocas e os boatos que aconteceram na favela, analisando o comportamento de cada morador. Tem muitas brincadeiras, às vezes se fala bem ou mal, mas tudo verdadeiro, apesar que muitos não gostam que o Judas deixe um ‘sabão’ prá ele.",
                        "No Cascalho também tem problemas. Muitas vezes tem brigas e, no meio da discussão, começam a falar das mães e as mães não têm nada a ver com isso. Tem também o asfalto que é perigoso e é preciso ter cuidado demais, principalmente com as crianças que são muito inocentes para atravessar a rua. No asfalto os carros descem em alta velocidade, muitos, porque correm de costume, outros, porque têm medo de passar pela favela. Às vezes tem uns malandros que não deixam os dias em paz. Às vezes é tiro para todos os lados e de vez em quando a polícia vem, mas não consegue pegar ninguém, porque eles correm e fogem para a casa deles e lá chutarão o balde e ficarão muito malucos.",
                        "Tem umas estórias que viraram lenda e correm no morro. Uma delas é a do homem que virava lobisomem. Dizem que em noite de lua cheia ele uivava, ficava coberto com um lençol e também comia tanajuras vivas. Ele corria pelos becos assustando as pessoas. Todo mundo tinha medo porque ele era grandão, todo cabeludo das pernas até o cérebro e com um bigode de arame fino. Ainda bem que atrás de mim ele não correu!",
                        "Outra estória conhecida é do 'Comanche', que era um cavalo marrom com malhas brancas. Era uma vez uma moca que se chama Adélia. Ela lá ia passando e o cavalo que se chama 'Comanche' disse: 'Boa noite Adélia'! E a Adélia correu para a casa da Consola e desmaiou. Também foi uma vez, com o moço que o apelido dele é Jó. O Jó tava passando e o cavalo disse: 'Aí Jó, como é bom viver neste mundo!' Pobre da Adélia e do Jó! Que loucura do cavalo! Nas lendas um cavalo pode conversar com alguém. No dia a dia a gente conversa com os animais e eles entendem, mas geralmente não nos respondem com palavras. Às vezes ficávamos sentados com Sô Tião que nos afirmava todas essas coisas. Quando duvidavam, ele mexia com as orelhas e dava uma gargalhada de lembrar prá sempre. Lembramos também outros bons momentos, principalmente as viagens quando o nosso time vai jogar em outros lugares. Merecia replay, como não temos fitas gravamos na memória.",
                        "É uma grande honra ter a nossa história contada em um livro onde muitas pessoas possam ler e reler a nossa vida. No relato feito por todos, tiramos muita coisa do baú e não teve nenhuma mentira cabeluda. Tudo que está escrito aqui é contado.",
                        "Também as lendas a maioria confirma, afinal acontece tanta coisa nesse mundo.",
                        "Texto coletivo escrito pelas crianças do Cascalho"]

let a_eng = "I took my mates three times, I took one of my cousin, I took one of my other cousin, of my brother in bed two times, of my sister holding an orange and an apple, of my brother with his medicine, my cousin took one of me; I took one of my mother's blouse, of Patricia two times, of Fernando two times, of Poliana, Patricia and Fernando; took one or my father, took one of my graduation picture, of ‘Little Tiaozinho’, I took one of me when | was little; of Athletico on the television, | took Athletico's goal six times."
let a_pt = "Eu tirei do meu parceiro três vezes, eu tirei do meu primo, da minha prima, do meu irmão na cama duas vezes, da minha irmã segurando uma laranja e uma maçã, do meu irmão com o remédio, meu primo tirou de mim; tirei da blusa da minha mãe, da Patricia duas vezes, do Fernando duas vezes, da Poliana, Patrícia e Fernando; tirei do meu pai, tirei do meu retrato de formatura. do Tiãozinho, tirei de mim quando eu era pequeno; da televisão que eu mais gosto e dos gols do Atlético seis vezes."

let b_eng = ["I was walking along the street and I found a fluorescent lamp.",
                "I was walking up the slope and I dropped the lamp. Suddenly there was a mixture of smoke and dust. The chickens flew up, the horses began to neigh and the goats began to bleat. Everything began to fly like cardboard in the wind.",
                "Suddenly, from inside the lamp, a genie appeared. Everybody was amazed and the genie said with his deep voice, ‘Those boys with no t-shirts and with green shorts have three wishes.’",
                "I replied, ‘Great! The first wish is that you organize this favela. The second is that you make our football pitch beautiful. The third is that we kids will become professional footballers’.",
                "Well, what they call an ugly favela was changed into a wonderful place, and the pitch turned into a stadium with green grass and we became famous players."]
let b_pt = "Eu andava pela rua e achei uma lâmpada fluorescente e peguei. Estava subindo a barranceira e deixei a lâmpada cair. De repente, ficou fumaça e poeira tudo misturado. As galinhas voaram para o alto, os cavalos começaram a relinchar os cabritos a berrar e tudo começou a voar feito papelão. De repente, de dentro da lâmpada surgiu um gênio. Todos nós ficamos espantados e o gênio com sua voz grossa disse: ‘Esses meninos, sem camisa e de short verde tem três desejos’. ‘Está bem! O primeiro desejo é que você arrume toda essa favela. O segundo, é deixar aquele campo e o pampilho todos arrumados. E o terceiro, que todos nós meninos, sejamos jogadores profissionais.’ Então, o que eles chamavam de favela feia e ridícula virou um lindo bairro, o campo virou um estádio, o caminho ficou gramado e os meninos viraram craques."

let c_eng = ["The helicopter flies over the city",
                "The city is full of people",
                "The people are full of children",
                "The kids are full of love"];
let c_pt = ["O ‘elicopido’ ‘avoa’ na cidade.",
                "A cidade é cheia de pessoas.",
                "As pessoas são cheias de filhos.",
                "Os filhos são cheios de carinho."]

let d_eng = ["Football for the people who have a lot is little",
                "And for the people who have a little, it’s a lot.",
                "It’s the reason why in my history I have big dreams."]
let d_pt = ["O futebol para quem tem muito é pouco",
                "E para quem them pouco é muito.",
                "Em razão da minha história eu sonho alto."];

let e_eng = ["I am I • Now and before • Now and always",
                "Always if I change and grow • I am I • Because I have my memories",
                "The good and the bad • Because I look like the others • But I am different",
                "Because I know me • And they know me too •",
                "Because when I get bigger I will do lots of things • In every way, I continue",
                "Being me in my own way"];
let e_pt = ["Eu sou eu • Agora e antes • Agora e sempre",
                "Mesmo que mude e cresça • Eu sou eu • Porque tenho minas recordações",
                "As boas e as más • Porque me pareço com os outros • Mas sou diferente •",
                "Porque me conheço • E me conhecem bem",
                "Porque quando for grande sou fazer muitas coisas • Acima de tudo, continuarei",
                "Sendo eu à minha maneira"]

let textContainer;
let currentLang = "pt";

function makeText(titleText,text,lang){
    textContainer.innerHTML = '';
    currentLang = lang;

    if(titleText !== ""){
    let title = document.createElement("h1");
        title.innerText = titleText;
        textContainer.appendChild(title);
    }

    if(Array.isArray(text)){
        for(i=0;i<text.length;i++){
            let prg = document.createElement("p");
                prg.innerText = text[i];
                textContainer.appendChild(prg);
        }
    } else {
        let prg = document.createElement("p");
                prg.innerText = text;
                textContainer.appendChild(prg);
    }
}

function makeTextbox(title_pt, pt,title_eng,eng){

    let textboxContainer = document.createElement("div");
        textboxContainer.id = "textbox_container";
        document.body.appendChild(textboxContainer);

        let textbox_container_space = document.createElement("div");
            textbox_container_space.classList.add("textbox_container_space");
            textboxContainer.appendChild(textbox_container_space);

        let newTextbox = document.createElement("div");
            newTextbox.id = "textbox";
            textboxContainer.appendChild(newTextbox);

            if(title_pt == intro_title_pt || title_pt == history_title_pt){
                textboxContainer.id = "textbox_container_index";
            } else {
                textboxContainer.style.position = "absolute";
                textboxContainer.style.left = 50 + "vw";
                textboxContainer.style.transform = "translate(-50%,0)"
            }

            textContainer = document.createElement("div");
                textContainer.id = "textContainer"
                newTextbox.appendChild(textContainer);

                makeText(title_pt, pt, "pt");

                textContainer.addEventListener("click",()=>{
                    if(currentLang === "pt"){
                        makeText(title_eng,eng, "eng")
                    } else {
                        makeText(title_pt,pt, "pt")
                    }
                })

        let closeX = document.createElement("p");
            closeX.innerText = "x";
            closeX.id = "textbox_x";
            newTextbox.appendChild(closeX);
            closeX.addEventListener("click",()=>{
                textboxContainer.style.display = "none";
            })

        let textbox_container_space2 = document.createElement("div");
            textbox_container_space2.classList.add("textbox_container_space");
            textboxContainer.appendChild(textbox_container_space2);
}